### ISSUE TITLE
Lacking proper setup for OSS

### ISSUE THREAD

**Issue by karimsa** [jaydenwindle/decode2017#39]
TODO:

 - Contribution guide (for internal + external use)
 - Issue template
 - License (I'm thinking Apache 2.0 if we intend on charging for this at some point? otherwise MIT)
 - Proper README
 - Documentation

**Comment by jaydenwindle** [comment]
Agreed. 

Can you split this up into multiple issues please? That will make it easier to keep track.

**Comment by karimsa** [comment]
Split into: #40, #41, #42, & #43.
