### ISSUE TITLE
Needs a contribution guide

### ISSUE THREAD

**Issue by karimsa** [jaydenwindle/decode2017#40]
We need a clearly defined contribution guide to outline how contributions should work (should be generic enough to be used internally as well as externally).

**Comment by vikrambombhi** [comment]
We talked to some shopify devs and they said a style guide will be coming out soon as well as a UI kit. We should definitely use it as soon as it comes out

**Comment by karimsa** [comment]
Certainly. I'm going to start writing parts of the contribution guide up and I'll open a PR - since I think we really need to start documenting the steps.
