### ISSUE TITLE
Needs OSS license

### ISSUE THREAD

**Issue by karimsa** [jaydenwindle/decode2017#42]
Possibles:

 - **Apache 2.0:** If we intend to go commercial.
 - **MIT:** If we couldn't care less.

**Update:** A good [link](https://choosealicense.com/) on both of these.

**Comment by jaydenwindle** [comment]
@VikramBombhi thoughts?

**Comment by karimsa** [comment]
We need this by EOD. I contacted BrowserStack for premium access since we're open source, but they need to see a license first.

**Comment by jaydenwindle** [comment]
@karimsa throw an Apache license on it then, wouldn't want to take going commercial out of the question.
