### ISSUE TITLE
Gemfile needs to be cleaned up

### ISSUE THREAD

**Issue by karimsa** [jaydenwindle/decode2017#55]
## Expected Behavior

`Gemfile` should be very clean and easy to read.

## Current Behavior

`Gemfile` is messy and full of unnecessary comments & some unused dependencies.

## Possible Solution

Do quick analysis of necessary/unnecessary gems and remove usless comments.

Perhaps separate gems into sections.

## Steps to Reproduce (for bugs)

N/a.

## Your Environment

N/a.

**Comment by jaydenwindle** [comment]
Will do.
